site_name: csoneira
site_url: https://csoneira.github.io/csoneira/  # Your GitHub Pages URL
repo_name: csoneira/csoneira
repo_url: https://github.com/cayesoneira/csoneira

nav:
  - Home: index.md
  - About: about.md
  - Milestones: milestones.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.indexes
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.superfences
  - pymdownx.highlight
